### ISSUE TITLE
<th> tag doesn't close

### ISSUE THREAD

**Issue by JavoByte** [uzyn/tag#2] opened 2014-10-09 19:08 UTC
All tags are closing correctly (so far) except this one. I type cmd+alt+. and nothing happens.

**Comment by uzyn** [comment] 2015-05-21 09:53
Unable to reproduce this bug.

Closing this issue as it has been opened for quite awhile.

Please reopen if this bug still exists.

Thanks.

**Closed by uzyn** 2015-05-21 09:53 UTC
